baseURL: ""
languageCode: en-us
title: gaspa
theme: PaperMod

menu:
  main:
    - identifier: home
      name: Home
      url: /
      weight: 10
    - identifier: projects
      name: Projects
      url: /projects
      weight: 20
    - identifier: experience
      name: Experience
      url: /experience
      weight: 30
    - identifier: search
      name: Search
      url: /search
      weight: 40

params:
  # theme
  showToc: true
  TocOpen: false
  ShowBreadCrumbs: true
  ShowCodeCopyButtons: true
  hideMeta: false

  # for enchanced SEO
  env: production

  # Home Page
  profileMode:
    enabled: true
    title: "Diogo Gaspar"
    subtitle: BSc. student in Computer Science and Engineering @ IST 🇵🇹<br>Full-Stack Developer @ DASI - IST
    imageUrl: "home/me.jpg"
    imageWidth: 220
    imageHeight: 220

  # List View
  hideDescriptionInList: false

  # cover image for posts
  cover:
    hiddenInList: false # hide on list pages and home
    hiddenInSingle: false # hide on single page

  socialIcons:
    - name: "email"
      url: "mailto:diogo@gaspa.pt"
    - name: "linkedin"
      url: "https://www.linkedin.com/in/diogomgaspar"
    - name: "github"
      url: "https://github.com/randomicecube"
    - name: "cv"
      url: "https://cv.gaspa.pt"

  # text search
  fuseOpts:
    isCaseSensitive: false
    shouldSort: true
    location: 0
    distance: 1000
    threshold: 0.4
    minMatchCharLength: 0
    keys: ["title", "permalink", "summary", "content"]

# for search using Fuse.js
outputs:
  home:
    - HTML
    - RSS
    - JSON

# allow HTML in MD
markup:
  goldmark:
    renderer:
      unsafe: true
